# Theme Selection
theme: minima

# Site settings
title: HOBOR
description: >- 
  R package for the analysis of HOBO weather station data.
baseurl: "/hoboR/" # the subpath of your site, e.g., /blog
url: "https://leboldus-lab.github.io/" # the base hostname & protocol for your site, e.g., http://example.com

# Build settings
markdown: kramdown
header_pages:
  - index.md
  - about.md
social_links:
  twitter: ricardoi
  github: ricardoi
