# Theme Selection
theme: minima

# Site settings
title: hoboR
author: 
#name: LeBoldus Lab
#email: @oregonstate.edu

description: >
  hoboR documentation by the LeBoldus lab at the Botany and Plant Pathology and  Forest Engineering, Resources and Management Department at Oregon State University. https://github.com/LeBoldus-Lab/hoboR 

baseurl: "/hoboR/" # the subpath of your site, e.g., /blog
url: "https://leboldus-lab.github.io/" 


# Build settings
markdown: kramdown
header_pages:
  - index.md
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima: 
  skin: auto

  #social_links:
  #  - { platform: x,			user_url: "https://twitter.com/" }
  #  - { platform: github, 		user_url: "https://github.com/" }
  #  - { platform: google_scholar,         user_url: "https://scholar.google.com/citations?user=SkBxudIAAAAJ&hl=en" }
