# Theme Selection
theme: minima

# Site settings
title: HOBOR
author: 
  name: ricardoi
  email: ricardo.alcalabriseno@oregonstate.edu

description: >-
  R package for the analysis of HOBO weather station data.
baseurl: "/hoboR/" # the subpath of your site, e.g., /blog
url: "https://leboldus-lab.github.io/" # the base hostname & protocol for your site, e.g., http://example.com

# Build settings
markdown: kramdown
header_pages:
  - index.md
  - about.md

minima: 
  skin: auto

social_links:
#  - { platform: x,			user_url: "https://twitter.com/" }
#  - { platform: github, 		user_url: "https://github.com/" }
#  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=SkBxudIAAAAJ&hl=en" }
