# Theme Selection
theme: minima

# Site settings
title: HOBOR
author: 
  name: leboldus-lab
#  email: hobor@oregonstate.edu

description: >
  An R package for the analysis of weather data. HOBOR is a specialized R package designed to streamline the processing of large datasets from HOBO weather stations and data loggers. 

baseurl: "/hoboR/" # the subpath of your site, e.g., /blog
url: "https://leboldus-lab.github.io/" # the base hostname & protocol for your site, e.g., http://example.com


# Build settings
markdown: kramdown
header_pages:
  - index.md
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima: 
  skin: auto

  #social_links:
  #  - { platform: x,			user_url: "https://twitter.com/" }
  #  - { platform: github, 		user_url: "https://github.com/" }
  #  - { platform: google_scholar,         user_url: "https://scholar.google.com/citations?user=SkBxudIAAAAJ&hl=en" }
